<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Core\Console\Command;
use App\Repositories\DeviceRepository;
use App\Services\DeviceService;
use Throwable;

/**
 * Register an ESP32 gate station and issue its credentials.
 *
 * The key is printed once and never again: the server keeps only a hash of
 * it, exactly as it does for a password. A key that is lost cannot be
 * recovered, only rotated — and rotating it means reflashing the station.
 *
 * @package App\Console\Commands
 * @version 1.0.0
 */
final class DeviceRegisterCommand extends Command
{
    protected string $name = 'device:register';
    protected string $description = 'Register a monitoring station and print its API key once.';
    protected string $usage = 'php bin/console device:register [--code=] [--name=] [--gate=entry|exit|both] [--location=] [--mac=] [--ip=] [--heartbeat=30]';

    /** @var list<string> */
    private const GATE_TYPES = ['entry', 'exit', 'both'];

    public function handle(): int
    {
        $gateType = $this->stringOption('gate', 'both');

        if (!in_array($gateType, self::GATE_TYPES, true)) {
            $this->output->error(sprintf(
                'The gate type must be one of %s; "%s" was given.',
                implode(', ', self::GATE_TYPES),
                $gateType
            ));

            return 1;
        }

        $code = $this->stringOption('code');
        $name = $this->stringOption('name');

        if ($name === '') {
            $name = $code !== ''
                ? $code
                : $this->output->ask('Station name', 'Gate station');
        }

        $attributes = [
            'device_code'        => $code,
            'device_name'        => $name,
            'gate_type'          => $gateType,
            'status'             => 'active',
            'heartbeat_interval' => $this->heartbeatInterval(),
        ];

        foreach (['location' => 'location', 'mac' => 'mac_address', 'ip' => 'allowed_ip', 'label' => 'gate_label'] as $option => $column) {
            $value = $this->stringOption($option);

            if ($value !== '') {
                $attributes[$column] = $value;
            }
        }

        try {
            $result = $this->service(DeviceService::class)->register($attributes, null);
        } catch (Throwable $e) {
            $this->reportFailure($e);

            return 1;
        }

        // The code may have been generated by the service, so it is read back
        // rather than echoed: the firmware needs the code the server actually
        // stored, not the one that was asked for.
        $stored = $this->service(DeviceRepository::class)->find($result['device_id']);

        $this->output->success(sprintf('Station registered with id %d.', $result['device_id']));
        $this->output->line();

        $this->output->table(
            ['Field', 'Value'],
            [
                ['Device code', (string) ($stored['device_code'] ?? $code)],
                ['Name', $name],
                ['Gate type', $gateType],
                ['Heartbeat', $this->heartbeatInterval() . ' s'],
            ]
        );

        $this->output->line();
        $this->output->info('API key: ' . $this->output->colour($result['api_key'], 'bold'));
        $this->output->line();
        $this->output->warning('This key is shown once. Only its hash is stored.');
        $this->output->comment('Put it in firmware/esp32/vams_station/secrets.h as DEVICE_API_KEY,');
        $this->output->comment('along with the device code as DEVICE_CODE, then flash the station.');

        return 0;
    }

    /**
     * The heartbeat interval in seconds.
     *
     * Bounded because the column is a SMALLINT and, more to the point, because
     * a one-second heartbeat from every gate would be a denial of service the
     * installation performs on itself.
     */
    private function heartbeatInterval(): int
    {
        $requested = $this->optionInt('heartbeat', 30);

        if ($requested < 5) {
            return 5;
        }

        return $requested > 3600 ? 3600 : $requested;
    }

    private function stringOption(string $name, string $default = ''): string
    {
        $value = $this->option($name, $default);

        return is_string($value) ? trim($value) : $default;
    }
}
